# Generated by Django 4.1.7 on 2023-04-03 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textindex',
            name='bigtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
