# Generated by Django 4.1.7 on 2023-04-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_textindex_bigtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textindex',
            old_name='bigtitle',
            new_name='big_title',
        ),
    ]
