# Generated by Django 4.1.7 on 2023-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_textindex_big_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='textindex',
            name='timage',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/main/textimg'),
        ),
    ]
