# Generated by Django 4.2 on 2023-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcards',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
