# Generated by Django 4.2 on 2023-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productcards_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcards',
            name='name',
        ),
        migrations.AddField(
            model_name='productcards',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
