# Generated by Django 4.2 on 2023-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customuser_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appealFIZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('Phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('appeal', models.TextField(verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обращение Физ. Лица',
                'verbose_name_plural': 'Обращения Физ. Лиц',
            },
        ),
        migrations.CreateModel(
            name='appealUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrFace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Лицо')),
                ('Fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Руководителя')),
                ('Phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('appeal', models.TextField(verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обращение Юр. Лица',
                'verbose_name_plural': 'Обращения Юр. Лиц',
            },
        ),
    ]
