# Generated by Django 4.2 on 2023-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appealfiz_appealur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcards',
            name='price',
        ),
        migrations.AddField(
            model_name='productcards',
            name='pagetitle',
            field=models.CharField(default=1, max_length=50, verbose_name='Название страницы(dev)'),
            preserve_default=False,
        ),
    ]
