# Generated by Django 4.2 on 2023-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_productcards_price_productcards_pagetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинки Животноводство',
                'verbose_name_plural': 'Картинки Животноводство',
            },
        ),
        migrations.CreateModel(
            name='ChillSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинки Отдых',
                'verbose_name_plural': 'Картинки Отдых',
            },
        ),
        migrations.CreateModel(
            name='PlantsSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинки Растеиеводство',
                'verbose_name_plural': 'Картинки Растеиеводство',
            },
        ),
        migrations.CreateModel(
            name='TradeSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинки Торговля',
                'verbose_name_plural': 'Картинки Торговля',
            },
        ),
        migrations.AlterField(
            model_name='productcards',
            name='pagetitle',
            field=models.CharField(editable=False, max_length=50, verbose_name='Название страницы(dev)'),
        ),
    ]
