# Generated by Django 4.2 on 2023-05-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_animalstext_chilltext_plantstext_tradetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('big_text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='chillsi',
            options={'verbose_name': 'Картинки Бани', 'verbose_name_plural': 'Картинки Бани'},
        ),
        migrations.AlterModelOptions(
            name='chilltext',
            options={'verbose_name': 'Текст Бани', 'verbose_name_plural': 'Тексты Бани'},
        ),
    ]
