# Generated by Django 4.2 on 2023-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_news_alter_chillsi_options_alter_chilltext_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ititle',
            field=models.CharField(default=1, max_length=255, verbose_name='Подпись'),
            preserve_default=False,
        ),
    ]
