# Generated by Django 4.2 on 2023-05-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_news_ititle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(to='main.imagen', verbose_name='Картинки'),
        ),
    ]
