# Generated by Django 4.2.1 on 2023-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_plantscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderFiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('Phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('Address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('Colvo', models.CharField(max_length=255, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказы Физ. Лиц',
                'verbose_name_plural': 'Заказы Физ. Лиц',
            },
        ),
        migrations.CreateModel(
            name='ProductOrderUr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('UrFace', models.CharField(max_length=255, verbose_name='Юр. Лицо')),
                ('FioRuk', models.CharField(max_length=255, verbose_name='ФИО Руководителя')),
                ('Phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('UrAddress', models.CharField(max_length=255, verbose_name='Юр. Адрес')),
                ('Colvo', models.CharField(max_length=255, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказы Юр. Лиц',
                'verbose_name_plural': 'Заказы Юр. Лиц',
            },
        ),
    ]
