# Generated by Django 4.2.1 on 2023-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_productorderfiz_productorderur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='main/static/main/subimg', verbose_name='Картинка')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Продукция Животновдство',
                'verbose_name_plural': 'Продукция Животновдство',
            },
        ),
        migrations.AlterField(
            model_name='plantscard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
