# Generated by Django 4.2.1 on 2023-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_animalscard_alter_plantscard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalscard',
            name='ed',
            field=models.CharField(default=1, max_length=5, verbose_name='Единица Измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantscard',
            name='ed',
            field=models.CharField(default=1, max_length=5, verbose_name='Единица Измерения'),
            preserve_default=False,
        ),
    ]
