# Generated by Django 4.2 on 2023-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_animalscard_ed_plantscard_ed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderur',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
