# Generated by Django 4.2 on 2023-06-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_articles',
            field=models.ManyToManyField(blank=True, to='main.news'),
        ),
    ]
